// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	model "github.com/inventory-management/model"
	mock "github.com/stretchr/testify/mock"
	gofr "gofr.dev/pkg/gofr"
)

// ProductDao is an autogenerated mock type for the ProductDao type
type ProductDao struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, product
func (_m *ProductDao) CreateProduct(ctx *gofr.Context, product model.Product) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gofr.Context, model.Product) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductDao creates a new instance of ProductDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductDao {
	mock := &ProductDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
